name:                Geo-Spline
version:             0.03
version_from:        lib/Geo/Spline.pm
abstract:            Calculate geographic locations between GPS fixes.
license:             perl
distribution_type:   module
requires:     
    vars:                          0
    strict:                        0
    constant:                      0
