name:                Geo-Spline
version:             0.01
version_from:        lib/Geo/Spline.pm
abstract:            Perl version of forward calculations
license:             perl
distribution_type:   module
requires:     
    vars:                          0
    strict:                        0
